# Academic Website Builder
# https://sourcethemes.com/academic/
#
# The presence of this file is for compatibility with Blogdown and Forestry.
# If you are not using those tools, this file may be deleted.
#
# The actual configuration files are stored in the `config/_default/` folder.
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
